### PR TITLE
Update change_license.html

### PR DESCRIPTION
**Pull request by tboy1337**
Added TON to accepted payment currency, very important to people in europe and possibly the US as using USDT can cause issues.

### CODE REVIEW

**Comment by masterking32** [comment]
We are not supporting TON overall, Only accept USDT, At this moment we are supporting TON just for some cases and It will removed later.

**Comment by masterking32** [comment]
If we say we accept TON, everyone will choose to pay with TON, and that's not ideal for us. Developers prefer to receive USDT, not TON because TON prices can fluctuate. If the price changes, I would have to pay developers according to the new rate when they want to cash out. While we do support TON, if you pay with TON, you'll receive 5-10% less USDT due to price fluctuations.

**Comment by tboy1337** [comment]
Yes I get there would be price fluctuations, maybe sell immediately on a
DEX to reduce fluctuations and only charge a small fee, or support more
networks for USDT like arbitrum, ethereum etc?

**Comment by masterking32** [comment]
Supporting other networks requires implementation and development, but right now, developing new modules is my priority. These modules are for the TON network, so anyone looking to use them must be using TON.

**Comment by tboy1337** [comment]
Maybe just convert the TON to USDT via a DEX then? There are many barriers
to sending crypto in Europe at the moment and if it's hard to buy many
people will just give up so more options will massively help.

**Pull request closed without merging**
